version: '3.7'

services:
  web:
    build: ./web
    ports:
      - 5000:80
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=web
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=web
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
