version: '3.7'

services:
  web:
    build: ./web
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_USER=web
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=web
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
