version: '3.7'

services:
  web:
    build: ./web
    ports:
      - 5000:80
    depends_on:
      - db
  db:
    image: mariadb:10.7
    environment:
      - MARIADB_ROOT_PASSWORD=rootpwd
      - MARIADB_USER=web
      - MARIADB_PASSWORD=password
      - MARIADB_DATABASE=web
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
